LOAD ..avl
CASE .\alpha_sweep.run
PLOP
g

OPER
1
x
st
.\a0.st
sb
.\a0.sb
t
p
d
h

2
x
st
.\a1.st
sb
.\a1.sb
t
h

3
x
st
.\a2.st
sb
.\a2.sb
t
h

4
x
st
.\a3.st
sb
.\a3.sb
t
h

5
x
st
.\a4.st
sb
.\a4.sb
t
h

6
x
st
.\a5.st
sb
.\a5.sb
t
h

7
x
st
.\a6.st
sb
.\a6.sb
t
h

8
x
st
.\a7.st
sb
.\a7.sb
t
h

9
x
st
.\a8.st
sb
.\a8.sb
t
h

10
x
st
.\a9.st
sb
.\a9.sb
t
h

11
x
st
.\a10.st
sb
.\a10.sb
t
h

12
x
st
.\a11.st
sb
.\a11.sb
t
h


Quit
