 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane MVP                                                   
     # Surfaces =   5
     # Strips   =  56
     # Vortices = 672

  Sref =  216.00       Cref =  48.000       Bref =  4.5000    
  Xref =  2.1000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.13357     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =   0.01641     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =  -0.01873
  CDtot =   0.13327
  CDvis =   0.00000     CDind = 0.1332679
  CLff  =  -0.00887     CDff  = 0.0152044    | Trefftz
  CYff  =   0.00000         e =    0.0176    | Plane  

   aileron         =   0.00000
   elevator        = -49.26004
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   0.592720    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.254128
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -1.094199
 y  mom.  Cm |    Cma =  -0.072241    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000002    Cnb =   1.350122

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   1.210549    CLr =   0.000000
 y  force CY |    CYp =   1.759958    CYq =   0.000000    CYr =   2.876886
 x' mom.  Cl'|    Clp =  -0.332395    Clq =  -0.000000    Clr =  18.746277
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -0.557675    Cmr =   0.000000
 z' mom.  Cn'|    Cnp = -16.376045    Cnq =  -0.000002    Cnr = -15.405023

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.001965   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =  -0.002962
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.001706
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.001166   Cmd3 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000000   Cnd3 =   0.016070
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000640 CDffd3 =  -0.000000
 span eff.   |    ed1 =   0.000000    ed2 =  -0.006304    ed3 =  -0.000000



 Neutral point  Xnp =   7.950246

 Clb Cnr / Clr Cnb  =   0.665995    (  > 1 if spirally stable )
