 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane MVP                                                   
     # Surfaces =   5
     # Strips   =  56
     # Vortices = 672

  Sref =  216.00       Cref =  48.000       Bref =  4.5000    
  Xref =  2.1000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =  -0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.16212     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.07735     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.04803
  CDtot =   0.17309
  CDvis =   0.00000     CDind = 0.1730854
  CLff  =   0.08482     CDff  = 0.0211340    | Trefftz
  CYff  =   0.00000         e =    1.1559    | Plane  

   aileron         =   0.00000
   elevator        = -58.39167
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   0.554525    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.238510
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -1.760291
 y  mom.  Cm |    Cma =  -0.073012    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000001    Cnb =   1.572748

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   1.183413    CLr =   0.000000
 y  force CY |    CYp =   3.984973    CYq =   0.000000    CYr =   2.072536
 x' mom.  Cl'|    Clp =  -0.341801    Clq =  -0.000000    Clr =  25.384270
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -0.549487    Cmr =   0.000000
 z' mom.  Cn'|    Cnp = -27.887323    Cnq =  -0.000001    Cnr = -14.401666

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.002353   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =  -0.002637
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.001356
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.001126   Cmd3 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000000   Cnd3 =   0.014293
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000350 CDffd3 =  -0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.066838    ed3 =   0.000000



 Neutral point  Xnp =   8.420007

 Clb Cnr / Clr Cnb  =   0.634999    (  > 1 if spirally stable )
