 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane MVP                                                   
     # Surfaces =   5
     # Strips   =  56
     # Vortices = 672

  Sref =  216.00       Cref =  48.000       Bref =  4.5000    
  Xref =  2.1000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.16378     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =   0.00000
  CZtot =  -0.08737     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.05451
  CDtot =   0.17744
  CDvis =   0.00000     CDind = 0.1774431
  CLff  =   0.09513     CDff  = 0.0226552    | Trefftz
  CYff  =   0.00000         e =    1.3564    | Plane  

   aileron         =   0.00000
   elevator        = -59.43724
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   0.549991    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.236398
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -1.829290
 y  mom.  Cm |    Cma =  -0.073102    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   1.610110

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   1.178015    CLr =   0.000001
 y  force CY |    CYp =   4.214095    CYq =  -0.000000    CYr =   1.940926
 x' mom.  Cl'|    Clp =  -0.390096    Clq =   0.000000    Clr =  26.112164
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -0.547736    Cmr =  -0.000001
 z' mom.  Cn'|    Cnp = -29.107046    Cnq =   0.000000    Cnr = -14.219831

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.002396   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =  -0.002595
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.001315
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.001119   Cmd3 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000000   Cnd3 =   0.014065
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000317 CDffd3 =  -0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.068734    ed3 =   0.000000



 Neutral point  Xnp =   8.479931

 Clb Cnr / Clr Cnb  =   0.618698    (  > 1 if spirally stable )
