 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane MVP                                                   
     # Surfaces =   5
     # Strips   =  56
     # Vortices = 672

  Sref =  216.00       Cref =  48.000       Bref =  4.5000    
  Xref =  2.1000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.14197     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.00476     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =  -0.00268
  CDtot =   0.14202
  CDvis =   0.00000     CDind = 0.1420207
  CLff  =   0.01203     CDff  = 0.0152941    | Trefftz
  CYff  =   0.00000         e =    0.0321    | Plane  

   aileron         =   0.00000
   elevator        = -51.25836
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   0.585194    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.251194
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -1.247568
 y  mom.  Cm |    Cma =  -0.072408    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000001    Cnb =   1.381336

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   1.207935    CLr =   0.000004
 y  force CY |    CYp =   2.274153    CYq =   0.000000    CYr =   2.759405
 x' mom.  Cl'|    Clp =  -0.264139    Clq =   0.000000    Clr =  20.240395
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -0.557038    Cmr =   0.000002
 z' mom.  Cn'|    Cnp = -19.000343    Cnq =  -0.000000    Cnr = -15.285387

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.002050   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =  -0.002899
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.001631
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.001162   Cmd3 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =   0.015723
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000577 CDffd3 =  -0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.010694    ed3 =   0.000000



 Neutral point  Xnp =   8.039200

 Clb Cnr / Clr Cnb  =   0.682060    (  > 1 if spirally stable )
