 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane MVP                                                   
     # Surfaces =   5
     # Strips   =  56
     # Vortices = 672

  Sref =  216.00       Cref =  48.000       Bref =  4.5000    
  Xref =  2.1000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =  -0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.14921     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =   0.00000
  CZtot =  -0.02582     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.01272
  CDtot =   0.15089
  CDvis =   0.00000     CDind = 0.1508942
  CLff  =   0.03291     CDff  = 0.0160908    | Trefftz
  CYff  =   0.00000         e =    0.2285    | Plane  

   aileron         =   0.00000
   elevator        = -53.27006
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   0.576926    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.247950
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -1.398486
 y  mom.  Cm |    Cma =  -0.072577    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   1.423160

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   1.203346    CLr =  -0.000001
 y  force CY |    CYp =   2.779101    CYq =   0.000000    CYr =   2.606260
 x' mom.  Cl'|    Clp =  -0.237278    Clq =  -0.000000    Clr =  21.721594
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -0.555724    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp = -21.592941    Cnq =  -0.000000    Cnr = -15.105294

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.002137   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =  -0.000000   CYd3 =  -0.002830
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =   0.000000   Cld3 =  -0.001554
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.001155   Cmd3 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000000   Cnd3 =   0.015347
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000513 CDffd3 =  -0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.031873    ed3 =   0.000000



 Neutral point  Xnp =   8.138391

 Clb Cnr / Clr Cnb  =   0.683348    (  > 1 if spirally stable )
