 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane MVP                                                   
     # Surfaces =   5
     # Strips   =  56
     # Vortices = 672

  Sref =  216.00       Cref =  48.000       Bref =  4.5000    
  Xref =  2.1000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.15239     Cltot =   0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -0.03628     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.02015
  CDtot =   0.15535
  CDvis =   0.00000     CDind = 0.1553517
  CLff  =   0.04333     CDff  = 0.0167528    | Trefftz
  CYff  =   0.00000         e =    0.3805    | Plane  

   aileron         =   0.00000
   elevator        = -54.28251
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   0.572585    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.246213
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -1.472797
 y  mom.  Cm |    Cma =  -0.072663    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   1.447992

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   1.200319    CLr =   0.000002
 y  force CY |    CYp =   3.027335    CYq =   0.000000    CYr =   2.516533
 x' mom.  Cl'|    Clp =  -0.238999    Clq =  -0.000000    Clr =  22.458138
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -0.554813    Cmr =  -0.000001
 z' mom.  Cn'|    Cnp = -22.875010    Cnq =  -0.000001    Cnr = -14.993022

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.002180   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =  -0.000000   CYd3 =  -0.002794
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.001515
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.001151   Cmd3 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =   0.015149
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000480 CDffd3 =  -0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.041957    ed3 =   0.000000



 Neutral point  Xnp =   8.191349

 Clb Cnr / Clr Cnb  =   0.679035    (  > 1 if spirally stable )
