 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane MVP                                                   
     # Surfaces =   5
     # Strips   =  56
     # Vortices = 672

  Sref =  216.00       Cref =  48.000       Bref =  4.5000    
  Xref =  2.1000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.15528     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.04668     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.02741
  CDtot =   0.15981
  CDvis =   0.00000     CDind = 0.1598099
  CLff  =   0.05373     CDff  = 0.0175894    | Trefftz
  CYff  =   0.00000         e =    0.5574    | Plane  

   aileron         =   0.00000
   elevator        = -55.30023
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   0.568143    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.244399
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -1.546221
 y  mom.  Cm |    Cma =  -0.072749    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000001    Cnb =   1.475401

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   1.196806    CLr =   0.000002
 y  force CY |    CYp =   3.272336    CYq =   0.000000    CYr =   2.418175
 x' mom.  Cl'|    Clp =  -0.250560    Clq =  -0.000000    Clr =  23.192387
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -0.553733    Cmr =   0.000001
 z' mom.  Cn'|    Cnp = -24.146378    Cnq =  -0.000000    Cnr = -14.866237

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.002224   CLd3 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =   0.000000   CYd3 =  -0.002756
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =  -0.000000   Cld3 =  -0.001476
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.001146   Cmd3 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000000   Cnd3 =   0.014944
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000448 CDffd3 =   0.000000
 span eff.   |    ed1 =   0.000000    ed2 =   0.050789    ed3 =  -0.000000



 Neutral point  Xnp =   8.246259

 Clb Cnr / Clr Cnb  =   0.671765    (  > 1 if spirally stable )
